spring:
  # datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_product?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

# rocketmq
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: product-producer-group
